// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FlightScraperClient is the client API for FlightScraper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlightScraperClient interface {
	GetSouthwestHeaders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SouthwestHeadersResponse, error)
}

type flightScraperClient struct {
	cc grpc.ClientConnInterface
}

func NewFlightScraperClient(cc grpc.ClientConnInterface) FlightScraperClient {
	return &flightScraperClient{cc}
}

func (c *flightScraperClient) GetSouthwestHeaders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SouthwestHeadersResponse, error) {
	out := new(SouthwestHeadersResponse)
	err := c.cc.Invoke(ctx, "/flights.FlightScraper/GetSouthwestHeaders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlightScraperServer is the server API for FlightScraper service.
// All implementations must embed UnimplementedFlightScraperServer
// for forward compatibility
type FlightScraperServer interface {
	GetSouthwestHeaders(context.Context, *Empty) (*SouthwestHeadersResponse, error)
	mustEmbedUnimplementedFlightScraperServer()
}

// UnimplementedFlightScraperServer must be embedded to have forward compatible implementations.
type UnimplementedFlightScraperServer struct {
}

func (UnimplementedFlightScraperServer) GetSouthwestHeaders(context.Context, *Empty) (*SouthwestHeadersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSouthwestHeaders not implemented")
}
func (UnimplementedFlightScraperServer) mustEmbedUnimplementedFlightScraperServer() {}

// UnsafeFlightScraperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlightScraperServer will
// result in compilation errors.
type UnsafeFlightScraperServer interface {
	mustEmbedUnimplementedFlightScraperServer()
}

func RegisterFlightScraperServer(s grpc.ServiceRegistrar, srv FlightScraperServer) {
	s.RegisterService(&FlightScraper_ServiceDesc, srv)
}

func _FlightScraper_GetSouthwestHeaders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightScraperServer).GetSouthwestHeaders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flights.FlightScraper/GetSouthwestHeaders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightScraperServer).GetSouthwestHeaders(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// FlightScraper_ServiceDesc is the grpc.ServiceDesc for FlightScraper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlightScraper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flights.FlightScraper",
	HandlerType: (*FlightScraperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSouthwestHeaders",
			Handler:    _FlightScraper_GetSouthwestHeaders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flight_scraping.proto",
}
